### ISSUE TITLE
Getting it worked on mac

### ISSUE THREAD

**Issue by RvBenthem** [pvanassen/ns-api#2]
Hey,

I'm a dutch student and i need to use the NS-api for a project. I am using an MacBook. but i am struggling for days. I hope someone can help me to getting it worked

**Comment by pvanassen** [comment]
What issues do you have? Can you supply a stacktrace or an implementation which does not work?

**Comment by RvBenthem** [comment]
Hi,

I have installed Maven and have imported the dependecies. I have uploaden 2 screenshots, maby you understand what is going wrong ?

**Comment by pvanassen** [comment]
I see no screenshots. Contact me at source at pvanassen dot nl and we'll take this conversation offline and do it in dutch.
