### ISSUE TITLE
Date vs LocalDateTime

### ISSUE THREAD

**Issue by skinkie** [pvanassen/ns-api#3]
Zou je de Date attributen kunnen bijwerken naar het inmiddels meer gangbare ZonedDateTime of gewoon direct LocalDateTime?

**Comment by pvanassen** [comment]
Het project compiled naar Java 7. LocalDateTime zit pas in Java 8. Gezien de grote hoeveelheid projecten die ik (helaas) in de praktijk tegen kom die nog op Java 7 draaien houd ik mijn open source projecten ook nog op Java 7.
